//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteKei.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLiteKei.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About_CheckOutOnGithub.
        /// </summary>
        public static string About_CheckOutOnGithub {
            get {
                return ResourceManager.GetString("About_CheckOutOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonText_Apply.
        /// </summary>
        public static string ButtonText_Apply {
            get {
                return ResourceManager.GetString("ButtonText_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonText_Cancel.
        /// </summary>
        public static string ButtonText_Cancel {
            get {
                return ResourceManager.GetString("ButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonText_Create.
        /// </summary>
        public static string ButtonText_Create {
            get {
                return ResourceManager.GetString("ButtonText_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonText_Execute.
        /// </summary>
        public static string ButtonText_Execute {
            get {
                return ResourceManager.GetString("ButtonText_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_CloseDatabase.
        /// </summary>
        public static string ContextMenuItem_CloseDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_CloseDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_DeleteDatabase.
        /// </summary>
        public static string ContextMenuItem_DeleteDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_DeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_DeleteIndex.
        /// </summary>
        public static string ContextMenuItem_DeleteIndex {
            get {
                return ResourceManager.GetString("ContextMenuItem_DeleteIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_DeleteTable.
        /// </summary>
        public static string ContextMenuItem_DeleteTable {
            get {
                return ResourceManager.GetString("ContextMenuItem_DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_DeleteTrigger.
        /// </summary>
        public static string ContextMenuItem_DeleteTrigger {
            get {
                return ResourceManager.GetString("ContextMenuItem_DeleteTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_DeleteView.
        /// </summary>
        public static string ContextMenuItem_DeleteView {
            get {
                return ResourceManager.GetString("ContextMenuItem_DeleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_EmptyTable.
        /// </summary>
        public static string ContextMenuItem_EmptyTable {
            get {
                return ResourceManager.GetString("ContextMenuItem_EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_NewDatabase.
        /// </summary>
        public static string ContextMenuItem_NewDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_NewIndex.
        /// </summary>
        public static string ContextMenuItem_NewIndex {
            get {
                return ResourceManager.GetString("ContextMenuItem_NewIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_NewTable.
        /// </summary>
        public static string ContextMenuItem_NewTable {
            get {
                return ResourceManager.GetString("ContextMenuItem_NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_NewTrigger.
        /// </summary>
        public static string ContextMenuItem_NewTrigger {
            get {
                return ResourceManager.GetString("ContextMenuItem_NewTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_NewView.
        /// </summary>
        public static string ContextMenuItem_NewView {
            get {
                return ResourceManager.GetString("ContextMenuItem_NewView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_OpenDatabase.
        /// </summary>
        public static string ContextMenuItem_OpenDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_OpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_OpenFileDirectory.
        /// </summary>
        public static string ContextMenuItem_OpenFileDirectory {
            get {
                return ResourceManager.GetString("ContextMenuItem_OpenFileDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_RenameDatabase.
        /// </summary>
        public static string ContextMenuItem_RenameDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_RenameDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_Label_Database.
        /// </summary>
        public static string CreatorWindow_Label_Database {
            get {
                return ResourceManager.GetString("CreatorWindow_Label_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_DatabaseName.
        /// </summary>
        public static string DatabaseGeneralTab_DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_DatabasePath.
        /// </summary>
        public static string DatabaseGeneralTab_DatabasePath {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_FileSize.
        /// </summary>
        public static string DatabaseGeneralTab_FileSize {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_NoTablesFound.
        /// </summary>
        public static string DatabaseGeneralTab_NoTablesFound {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_NoTablesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_Records.
        /// </summary>
        public static string DatabaseGeneralTab_Records {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_TableColumns.
        /// </summary>
        public static string DatabaseGeneralTab_TableColumns {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_TableName.
        /// </summary>
        public static string DatabaseGeneralTab_TableName {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_TableRecords.
        /// </summary>
        public static string DatabaseGeneralTab_TableRecords {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_TableRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_Tables.
        /// </summary>
        public static string DatabaseGeneralTab_Tables {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Documentation {
            get {
                object obj = ResourceManager.GetObject("Documentation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexCreator_ColumnAction_Ascending.
        /// </summary>
        public static string IndexCreator_ColumnAction_Ascending {
            get {
                return ResourceManager.GetString("IndexCreator_ColumnAction_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexCreator_ColumnAction_Descending.
        /// </summary>
        public static string IndexCreator_ColumnAction_Descending {
            get {
                return ResourceManager.GetString("IndexCreator_ColumnAction_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexCreator_ColumnAction_DoNotUse.
        /// </summary>
        public static string IndexCreator_ColumnAction_DoNotUse {
            get {
                return ResourceManager.GetString("IndexCreator_ColumnAction_DoNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexCreator_GroupBoxHeader_ColumnActions.
        /// </summary>
        public static string IndexCreator_GroupBoxHeader_ColumnActions {
            get {
                return ResourceManager.GetString("IndexCreator_GroupBoxHeader_ColumnActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexCreator_Label_IndexName.
        /// </summary>
        public static string IndexCreator_Label_IndexName {
            get {
                return ResourceManager.GetString("IndexCreator_Label_IndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexCreator_StatusInfo_InvalidModel.
        /// </summary>
        public static string IndexCreator_StatusInfo_InvalidModel {
            get {
                return ResourceManager.GetString("IndexCreator_StatusInfo_InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexCreator_StatusInfo_Success.
        /// </summary>
        public static string IndexCreator_StatusInfo_Success {
            get {
                return ResourceManager.GetString("IndexCreator_StatusInfo_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexGeneralTab_IndexCreateStatement.
        /// </summary>
        public static string IndexGeneralTab_IndexCreateStatement {
            get {
                return ResourceManager.GetString("IndexGeneralTab_IndexCreateStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexGeneralTab_IndexName.
        /// </summary>
        public static string IndexGeneralTab_IndexName {
            get {
                return ResourceManager.GetString("IndexGeneralTab_IndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexGeneralTab_IsUnique.
        /// </summary>
        public static string IndexGeneralTab_IsUnique {
            get {
                return ResourceManager.GetString("IndexGeneralTab_IsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_About.
        /// </summary>
        public static string MenuItemHeader_About {
            get {
                return ResourceManager.GetString("MenuItemHeader_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_CreateIndex.
        /// </summary>
        public static string MenuItemHeader_CreateIndex {
            get {
                return ResourceManager.GetString("MenuItemHeader_CreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_CreateTable.
        /// </summary>
        public static string MenuItemHeader_CreateTable {
            get {
                return ResourceManager.GetString("MenuItemHeader_CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_CreateTrigger.
        /// </summary>
        public static string MenuItemHeader_CreateTrigger {
            get {
                return ResourceManager.GetString("MenuItemHeader_CreateTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_CreateView.
        /// </summary>
        public static string MenuItemHeader_CreateView {
            get {
                return ResourceManager.GetString("MenuItemHeader_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Documentation.
        /// </summary>
        public static string MenuItemHeader_Documentation {
            get {
                return ResourceManager.GetString("MenuItemHeader_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Exit.
        /// </summary>
        public static string MenuItemHeader_Exit {
            get {
                return ResourceManager.GetString("MenuItemHeader_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_File.
        /// </summary>
        public static string MenuItemHeader_File {
            get {
                return ResourceManager.GetString("MenuItemHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Help.
        /// </summary>
        public static string MenuItemHeader_Help {
            get {
                return ResourceManager.GetString("MenuItemHeader_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_NewDatabase.
        /// </summary>
        public static string MenuItemHeader_NewDatabase {
            get {
                return ResourceManager.GetString("MenuItemHeader_NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_OpenDatabase.
        /// </summary>
        public static string MenuItemHeader_OpenDatabase {
            get {
                return ResourceManager.GetString("MenuItemHeader_OpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Preferences.
        /// </summary>
        public static string MenuItemHeader_Preferences {
            get {
                return ResourceManager.GetString("MenuItemHeader_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_QueryEditor.
        /// </summary>
        public static string MenuItemHeader_QueryEditor {
            get {
                return ResourceManager.GetString("MenuItemHeader_QueryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Tools.
        /// </summary>
        public static string MenuItemHeader_Tools {
            get {
                return ResourceManager.GetString("MenuItemHeader_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_DatabaseDeleteWarning.
        /// </summary>
        public static string MessageBox_DatabaseDeleteWarning {
            get {
                return ResourceManager.GetString("MessageBox_DatabaseDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_EmptyTable.
        /// </summary>
        public static string MessageBox_EmptyTable {
            get {
                return ResourceManager.GetString("MessageBox_EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_IndexDeleteWarning.
        /// </summary>
        public static string MessageBox_IndexDeleteWarning {
            get {
                return ResourceManager.GetString("MessageBox_IndexDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_IndexUniquenessWarning.
        /// </summary>
        public static string MessageBox_IndexUniquenessWarning {
            get {
                return ResourceManager.GetString("MessageBox_IndexUniquenessWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_NameChangeWarning.
        /// </summary>
        public static string MessageBox_NameChangeWarning {
            get {
                return ResourceManager.GetString("MessageBox_NameChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_ReindexTable.
        /// </summary>
        public static string MessageBox_ReindexTable {
            get {
                return ResourceManager.GetString("MessageBox_ReindexTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_TableDeleteWarning.
        /// </summary>
        public static string MessageBox_TableDeleteWarning {
            get {
                return ResourceManager.GetString("MessageBox_TableDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_TriggerDeleteWarning.
        /// </summary>
        public static string MessageBox_TriggerDeleteWarning {
            get {
                return ResourceManager.GetString("MessageBox_TriggerDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_ViewDeleteWarning.
        /// </summary>
        public static string MessageBox_ViewDeleteWarning {
            get {
                return ResourceManager.GetString("MessageBox_ViewDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessaxeBoxTitle_DatabaseDeletion.
        /// </summary>
        public static string MessageBoxTitle_DatabaseDeletion {
            get {
                return ResourceManager.GetString("MessageBoxTitle_DatabaseDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoxTitle_EmptyTable.
        /// </summary>
        public static string MessageBoxTitle_EmptyTable {
            get {
                return ResourceManager.GetString("MessageBoxTitle_EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoxTitle_IndexDeletion.
        /// </summary>
        public static string MessageBoxTitle_IndexDeletion {
            get {
                return ResourceManager.GetString("MessageBoxTitle_IndexDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoxTitle_ReindexTable.
        /// </summary>
        public static string MessageBoxTitle_ReindexTable {
            get {
                return ResourceManager.GetString("MessageBoxTitle_ReindexTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoxTitle_TableDeletion.
        /// </summary>
        public static string MessageBoxTitle_TableDeletion {
            get {
                return ResourceManager.GetString("MessageBoxTitle_TableDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoxTitle_TriggerDeletion.
        /// </summary>
        public static string MessageBoxTitle_TriggerDeletion {
            get {
                return ResourceManager.GetString("MessageBoxTitle_TriggerDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoxTitle_ViewDeletion.
        /// </summary>
        public static string MessageBoxTitle_ViewDeletion {
            get {
                return ResourceManager.GetString("MessageBoxTitle_ViewDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences_ApplicationTheme.
        /// </summary>
        public static string Preferences_ApplicationTheme {
            get {
                return ResourceManager.GetString("Preferences_ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences_GroupBoxHeader_Languages.
        /// </summary>
        public static string Preferences_GroupBoxHeader_Languages {
            get {
                return ResourceManager.GetString("Preferences_GroupBoxHeader_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences_GroupBoxHeader_Themes.
        /// </summary>
        public static string Preferences_GroupBoxHeader_Themes {
            get {
                return ResourceManager.GetString("Preferences_GroupBoxHeader_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences_Language.
        /// </summary>
        public static string Preferences_Language {
            get {
                return ResourceManager.GetString("Preferences_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences_Language_English.
        /// </summary>
        public static string Preferences_Language_English {
            get {
                return ResourceManager.GetString("Preferences_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences_Language_German.
        /// </summary>
        public static string Preferences_Language_German {
            get {
                return ResourceManager.GetString("Preferences_Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences_LanguageChangeInfo.
        /// </summary>
        public static string Preferences_LanguageChangeInfo {
            get {
                return ResourceManager.GetString("Preferences_LanguageChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryEditor_FileLoadFailed.
        /// </summary>
        public static string QueryEditor_FileLoadFailed {
            get {
                return ResourceManager.GetString("QueryEditor_FileLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryEditor_FileSaveFailed.
        /// </summary>
        public static string QueryEditor_FileSaveFailed {
            get {
                return ResourceManager.GetString("QueryEditor_FileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryEditor_Label_Database.
        /// </summary>
        public static string QueryEditor_Label_Database {
            get {
                return ResourceManager.GetString("QueryEditor_Label_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryEditor_LoadQuery.
        /// </summary>
        public static string QueryEditor_LoadQuery {
            get {
                return ResourceManager.GetString("QueryEditor_LoadQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryEditor_NoDatabaseSelected.
        /// </summary>
        public static string QueryEditor_NoDatabaseSelected {
            get {
                return ResourceManager.GetString("QueryEditor_NoDatabaseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryEditor_SaveQuery.
        /// </summary>
        public static string QueryEditor_SaveQuery {
            get {
                return ResourceManager.GetString("QueryEditor_SaveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabContent_GroupBoxHeader_About.
        /// </summary>
        public static string TabContent_GroupBoxHeader_About {
            get {
                return ResourceManager.GetString("TabContent_GroupBoxHeader_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabContent_GroupBoxHeader_Columns.
        /// </summary>
        public static string TabContent_GroupBoxHeader_Columns {
            get {
                return ResourceManager.GetString("TabContent_GroupBoxHeader_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabContent_GroupBoxHeader_Columns.
        /// </summary>
        public static string TabContent_GroupBoxHeader_Tables {
            get {
                return ResourceManager.GetString("TabContent_GroupBoxHeader_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabHeader_General.
        /// </summary>
        public static string TabHeader_General {
            get {
                return ResourceManager.GetString("TabHeader_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabHeader_GeneralIndex.
        /// </summary>
        public static string TabHeader_GeneralIndex {
            get {
                return ResourceManager.GetString("TabHeader_GeneralIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabHeader_GeneralTable.
        /// </summary>
        public static string TabHeader_GeneralTable {
            get {
                return ResourceManager.GetString("TabHeader_GeneralTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabHeader_GeneralTrigger.
        /// </summary>
        public static string TabHeader_GeneralTrigger {
            get {
                return ResourceManager.GetString("TabHeader_GeneralTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabHeader_GeneralView.
        /// </summary>
        public static string TabHeader_GeneralView {
            get {
                return ResourceManager.GetString("TabHeader_GeneralView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabHeader_TableRecords.
        /// </summary>
        public static string TabHeader_TableRecords {
            get {
                return ResourceManager.GetString("TabHeader_TableRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_ButtonText_AddColumn.
        /// </summary>
        public static string TableCreator_ButtonText_AddColumn {
            get {
                return ResourceManager.GetString("TableCreator_ButtonText_AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_ForeignKey.
        /// </summary>
        public static string TableCreator_ForeignKey {
            get {
                return ResourceManager.GetString("TableCreator_ForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_Label_TableName.
        /// </summary>
        public static string TableCreator_Label_Default {
            get {
                return ResourceManager.GetString("TableCreator_Label_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_Label_TableName.
        /// </summary>
        public static string TableCreator_Label_TableName {
            get {
                return ResourceManager.GetString("TableCreator_Label_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_NoDatabaseSelected.
        /// </summary>
        public static string TableCreator_NoDatabaseSelected {
            get {
                return ResourceManager.GetString("TableCreator_NoDatabaseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_References.
        /// </summary>
        public static string TableCreator_References {
            get {
                return ResourceManager.GetString("TableCreator_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_TabHeader_Columns.
        /// </summary>
        public static string TableCreator_TabHeader_Columns {
            get {
                return ResourceManager.GetString("TableCreator_TabHeader_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_TabHeader_ForeignKeys.
        /// </summary>
        public static string TableCreator_TabHeader_ForeignKeys {
            get {
                return ResourceManager.GetString("TableCreator_TabHeader_ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_TableCreateSuccess.
        /// </summary>
        public static string TableCreator_TableCreateSuccess {
            get {
                return ResourceManager.GetString("TableCreator_TableCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_ButtonText_Empty.
        /// </summary>
        public static string TableGeneralTab_ButtonText_Empty {
            get {
                return ResourceManager.GetString("TableGeneralTab_ButtonText_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_ButtonText_Reindex.
        /// </summary>
        public static string TableGeneralTab_ButtonText_Reindex {
            get {
                return ResourceManager.GetString("TableGeneralTab_ButtonText_Reindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_ColumnName.
        /// </summary>
        public static string TableGeneralTab_ColumnName {
            get {
                return ResourceManager.GetString("TableGeneralTab_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_Columns.
        /// </summary>
        public static string TableGeneralTab_Columns {
            get {
                return ResourceManager.GetString("TableGeneralTab_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_DataType.
        /// </summary>
        public static string TableGeneralTab_DataType {
            get {
                return ResourceManager.GetString("TableGeneralTab_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_Default.
        /// </summary>
        public static string TableGeneralTab_Default {
            get {
                return ResourceManager.GetString("TableGeneralTab_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_NoColumnsFound.
        /// </summary>
        public static string TableGeneralTab_NoColumnsFound {
            get {
                return ResourceManager.GetString("TableGeneralTab_NoColumnsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_Records.
        /// </summary>
        public static string TableGeneralTab_Records {
            get {
                return ResourceManager.GetString("TableGeneralTab_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_TableCreateStatement.
        /// </summary>
        public static string TableGeneralTab_TableCreateStatement {
            get {
                return ResourceManager.GetString("TableGeneralTab_TableCreateStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_TableName.
        /// </summary>
        public static string TableGeneralTab_TableName {
            get {
                return ResourceManager.GetString("TableGeneralTab_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableRecordsTab_Filter.
        /// </summary>
        public static string TableRecordsTab_Filter {
            get {
                return ResourceManager.GetString("TableRecordsTab_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_CloseDatabase.
        /// </summary>
        public static string Tooltip_CloseDatabase {
            get {
                return ResourceManager.GetString("Tooltip_CloseDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_CreateIndex.
        /// </summary>
        public static string Tooltip_CreateIndex {
            get {
                return ResourceManager.GetString("Tooltip_CreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_CreateTable.
        /// </summary>
        public static string Tooltip_CreateTable {
            get {
                return ResourceManager.GetString("Tooltip_CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_CreateTrigger.
        /// </summary>
        public static string Tooltip_CreateTrigger {
            get {
                return ResourceManager.GetString("Tooltip_CreateTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_NewView.
        /// </summary>
        public static string Tooltip_CreateView {
            get {
                return ResourceManager.GetString("Tooltip_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_DeleteDatabase.
        /// </summary>
        public static string Tooltip_DeleteDatabase {
            get {
                return ResourceManager.GetString("Tooltip_DeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_NewDatabase.
        /// </summary>
        public static string Tooltip_NewDatabase {
            get {
                return ResourceManager.GetString("Tooltip_NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_OpenDatabase.
        /// </summary>
        public static string Tooltip_OpenDatabase {
            get {
                return ResourceManager.GetString("Tooltip_OpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_WriteSQLStatement.
        /// </summary>
        public static string Tooltip_WriteSQLStatement {
            get {
                return ResourceManager.GetString("Tooltip_WriteSQLStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeItem_Indexes.
        /// </summary>
        public static string TreeItem_Indexes {
            get {
                return ResourceManager.GetString("TreeItem_Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeItem_Tables.
        /// </summary>
        public static string TreeItem_Tables {
            get {
                return ResourceManager.GetString("TreeItem_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeItem_Triggers.
        /// </summary>
        public static string TreeItem_Triggers {
            get {
                return ResourceManager.GetString("TreeItem_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeItem_Views.
        /// </summary>
        public static string TreeItem_Views {
            get {
                return ResourceManager.GetString("TreeItem_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerCreator_GroupBoxHeader_Columns.
        /// </summary>
        public static string TriggerCreator_GroupBoxHeader_Columns {
            get {
                return ResourceManager.GetString("TriggerCreator_GroupBoxHeader_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerCreator_GroupBoxHeader_EventDefinition.
        /// </summary>
        public static string TriggerCreator_GroupBoxHeader_EventDefinition {
            get {
                return ResourceManager.GetString("TriggerCreator_GroupBoxHeader_EventDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerCreator_GroupBoxHeader_TriggerActions.
        /// </summary>
        public static string TriggerCreator_GroupBoxHeader_TriggerActions {
            get {
                return ResourceManager.GetString("TriggerCreator_GroupBoxHeader_TriggerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerCreator_GroupBoxHeader_WhenExpression.
        /// </summary>
        public static string TriggerCreator_GroupBoxHeader_WhenExpression {
            get {
                return ResourceManager.GetString("TriggerCreator_GroupBoxHeader_WhenExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerCreator_Label_TriggerName.
        /// </summary>
        public static string TriggerCreator_Label_TriggerName {
            get {
                return ResourceManager.GetString("TriggerCreator_Label_TriggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerCreator_StatusInfo_InvalidModel.
        /// </summary>
        public static string TriggerCreator_StatusInfo_InvalidModel {
            get {
                return ResourceManager.GetString("TriggerCreator_StatusInfo_InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerCreator_StatusInfo_Success.
        /// </summary>
        public static string TriggerCreator_StatusInfo_Success {
            get {
                return ResourceManager.GetString("TriggerCreator_StatusInfo_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerGeneralTab_Button_UpdateDefinition.
        /// </summary>
        public static string TriggerGeneralTab_Button_UpdateDefinition {
            get {
                return ResourceManager.GetString("TriggerGeneralTab_Button_UpdateDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerGeneralTab_TriggerCreateStatement.
        /// </summary>
        public static string TriggerGeneralTab_TriggerCreateStatement {
            get {
                return ResourceManager.GetString("TriggerGeneralTab_TriggerCreateStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerGeneralTab_TriggerName.
        /// </summary>
        public static string TriggerGeneralTab_TriggerName {
            get {
                return ResourceManager.GetString("TriggerGeneralTab_TriggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnhandledException.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnhandledException_Title.
        /// </summary>
        public static string UnhandledException_Title {
            get {
                return ResourceManager.GetString("UnhandledException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewCreator_InvalidStatement.
        /// </summary>
        public static string ViewCreator_InvalidStatement {
            get {
                return ResourceManager.GetString("ViewCreator_InvalidStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewCreator_Label_ViewDefinition.
        /// </summary>
        public static string ViewCreator_Label_ViewDefinition {
            get {
                return ResourceManager.GetString("ViewCreator_Label_ViewDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewCreator_Label_ViewName.
        /// </summary>
        public static string ViewCreator_Label_ViewName {
            get {
                return ResourceManager.GetString("ViewCreator_Label_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewCreator_ViewCreateSuccess.
        /// </summary>
        public static string ViewCreator_ViewCreateSuccess {
            get {
                return ResourceManager.GetString("ViewCreator_ViewCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewGeneralTab_Button_UpdateDefinition.
        /// </summary>
        public static string ViewGeneralTab_Button_UpdateDefinition {
            get {
                return ResourceManager.GetString("ViewGeneralTab_Button_UpdateDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewGeneralTab_CouldNotLoadResults.
        /// </summary>
        public static string ViewGeneralTab_CouldNotLoadResults {
            get {
                return ResourceManager.GetString("ViewGeneralTab_CouldNotLoadResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewGeneralTab_InvalidStatement.
        /// </summary>
        public static string ViewGeneralTab_InvalidStatement {
            get {
                return ResourceManager.GetString("ViewGeneralTab_InvalidStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewGeneralTab_ViewContent.
        /// </summary>
        public static string ViewGeneralTab_ViewContent {
            get {
                return ResourceManager.GetString("ViewGeneralTab_ViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewGeneralTab_ViewDefinition.
        /// </summary>
        public static string ViewGeneralTab_ViewDefinition {
            get {
                return ResourceManager.GetString("ViewGeneralTab_ViewDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewGeneralTab_ViewName.
        /// </summary>
        public static string ViewGeneralTab_ViewName {
            get {
                return ResourceManager.GetString("ViewGeneralTab_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_About.
        /// </summary>
        public static string WindowTitle_About {
            get {
                return ResourceManager.GetString("WindowTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_IndexCreator.
        /// </summary>
        public static string WindowTitle_IndexCreator {
            get {
                return ResourceManager.GetString("WindowTitle_IndexCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_Preferences.
        /// </summary>
        public static string WindowTitle_Preferences {
            get {
                return ResourceManager.GetString("WindowTitle_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_QueryEditor.
        /// </summary>
        public static string WindowTitle_QueryEditor {
            get {
                return ResourceManager.GetString("WindowTitle_QueryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_SelectQueryCreator.
        /// </summary>
        public static string WindowTitle_SelectQueryCreator {
            get {
                return ResourceManager.GetString("WindowTitle_SelectQueryCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_TableCreator.
        /// </summary>
        public static string WindowTitle_TableCreator {
            get {
                return ResourceManager.GetString("WindowTitle_TableCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_TriggerCreator.
        /// </summary>
        public static string WindowTitle_TriggerCreator {
            get {
                return ResourceManager.GetString("WindowTitle_TriggerCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_ViewCreator.
        /// </summary>
        public static string WindowTitle_ViewCreator {
            get {
                return ResourceManager.GetString("WindowTitle_ViewCreator", resourceCulture);
            }
        }
    }
}
